name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:

        runs-on: ubuntu-latest

        strategy:
          matrix:
            otp:
              - erlang:23.0.3
              - erlang:22.3
              - erlang:21.3

        container:
            image: ${{ matrix.otp }}

        steps:
        - uses: actions/checkout@v1
        - name: Code dialyzer
          run: |
            # check validity of appup file
            erl -noshell -eval "{ok,_}=file:consult('src/esockd.appup.src')" -s init stop
            make xref
            make dialyzer
        - name: Run tests
          run: |
            make eunit
            make ct
            make cover
        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls
        - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
          if: failure()
          with:
            name: logs
            path: _build/test/logs
